### ISSUE TITLE
Circular particles in RxRx19a

### ISSUE THREAD

**Issue by Sadegh-Saberian** [recursionpharma/rxrx-datasets#3]
Hi,

I am working on the RxRx19a dataset and found that there are round object, notable present in 4 of 5 channels. I have attached a pic of them. Could you help understand what they actually are? It seems that there is a corelation between these objects and the Active SARS-CoV-2 condition in the dataset.

<img width="582" alt="Screen Shot 2020-08-08 at 11 43 46 AM" src="https://user-images.githubusercontent.com/39047812/89717587-d74c0400-d96c-11ea-9cad-ab5c70b7bd59.png">

**Comment by ihaque** [comment]
Apologies for the slow response @Sadegh-Saberian!

These are almost certainly dead cells caused by the viral infection -- you're seeing [cytopathic effects](https://en.wikipedia.org/wiki/Cytopathic_effect), which is why you only see them in the Active SARS-CoV-2 condition; the other conditions should not have viable virus in them.
